"""Centralized defaults and static limits used by the knowledge-search app.

Keeping defaults here prevents the CLI, indexer, chunker, and web API from
drifting apart when a runtime setting changes.
"""

from __future__ import annotations

from pathlib import Path


# Chunking defaults.  The core chunk size is intentionally 1600 characters.
DEFAULT_CORE_CHUNK_CHARS = 1600
DEFAULT_CHUNK_OVERLAP_CHARS = 200
# With 1600-character cores, merge tails shorter than 400 characters and
# allow semantic groups to grow to at most two cores (3200 characters).
DEFAULT_MIN_CHUNK_CHARS = 400
DEFAULT_MAX_CHUNK_CHARS = 3200
DEFAULT_SEMANTIC_MERGE_THRESHOLD = 0.80
DEFAULT_MAX_CHUNK_TOKENS = 8192

# Embedding defaults shared by the CLI and EmbeddingSettings.
DEFAULT_EMBEDDING_MODEL = "Qwen/Qwen3-Embedding-0.6B"
DEFAULT_EMBEDDING_BASE_URL = "http://127.0.0.1:8000"
DEFAULT_EMBEDDING_PROTOCOL = "auto"
DEFAULT_EMBEDDING_DIMENSION = 1024
DEFAULT_EMBEDDING_BATCH_SIZE = 8
DEFAULT_CLI_EMBEDDING_BATCH_SIZE = 16
DEFAULT_EMBEDDING_TIMEOUT_SECONDS = 120.0
DEFAULT_EMBEDDING_MAX_RETRIES = 10
DEFAULT_EMBEDDING_RETRY_DELAY_SECONDS = 1.0
DEFAULT_QUERY_INSTRUCTION = "根据用户问题，从知识库中检索能够直接回答问题的相关文档片段"
CODE_QUERY_INSTRUCTION = "根据用户问题，从代码库中检索相关的实现、函数、类或调用逻辑"
DOCUMENT_INPUT_TEMPLATE_VERSION = "qwen3-document-v2-strict-length"

# RAG defaults.
DEFAULT_RAG_TOP_K = 20
DEFAULT_RAG_MAX_CONTEXT_CHARS = 12_000
DEFAULT_RAG_TEMPERATURE = 0.0

# General CLI and service defaults.
DEFAULT_DB_PATH = Path("data/knowledge.db")
DEFAULT_LOG_PATH = Path("logs/app.log")
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_DATASET_SPLIT = "train"
DEFAULT_UPLOAD_DIR = Path("uploads")
DEFAULT_WEB_HOST = "127.0.0.1"
DEFAULT_WEB_PORT = 8000
DEFAULT_SEARCH_LIMIT = 10
DEFAULT_MAX_SEARCH_LIMIT = 100
DEFAULT_CHUNK_WINDOW_RADIUS = 1
DEFAULT_CHARACTER_NGRAM_SIZE = 2
DEFAULT_CHARACTER_NGRAM_LIMIT = 64
DEFAULT_MAX_FILES = 0
DEFAULT_JSON_PREVIEW_LIMIT = 5

# JSON parser defaults.
DEFAULT_READ_SIZE = 64 * 1024
DEFAULT_JSON_MAX_RECORDS = 100
DEFAULT_JSON_MAX_PATHS = 10_000
DEFAULT_JSON_MAX_DEPTH = 20
DEFAULT_UNLIMITED_SIZE = 0
DEFAULT_JSON_MAX_SIZE = 512 * 1024 * 1024
DEFAULT_JSON_RECORD_PROBE_SIZE = 512 * 1024 * 1024

# Web request limits.
MAX_UPLOAD_BYTES = 512 * 1024 * 1024
MAX_MULTIPART_OVERHEAD = 64 * 1024
MAX_JSON_BODY_BYTES = 1_000_000
MAX_INDEX_PATHS = 100
MAX_QUESTION_CHARS = 10_000
MAX_CHUNK_SIZE = 100_000
MAX_CONTEXT_CHARS = 100_000
DEFAULT_DATASET_FORMAT_PROBE_SIZE = 8192
DEFAULT_LLM_TIMEOUT_SECONDS = 60.0
